version: '3.9'

services:
  frontend:
    image: ronitacr20354.azurecr.io/frontend:latest
    ports:
      - "3000:80"

  backend:
    image: ronitacr20354.azurecr.io/backend:latest
    ports:
      - "8000:8000"
